tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_11_device_/job:localhost/replica:0/task:0/device:CPU:0}} 

    Received incompatible tensor at flattened index 0 from table 'uniform_table'.  
    Specification has   (dtype, shape): (int32, [?]).  
    Tensor has          (dtype, shape): (int32, [2,1]).


Table signature: 
0: Tensor<name: 'step_type/step_type', dtype: int32, shape: [?]>, 
1: Tensor<name: 'observation/observation', dtype: float, shape: [?,3]>, 
2: Tensor<name: 'action/action', dtype: int32, shape: [?]>, 
3: Tensor<name: 'next_step_type/step_type', dtype: int32, shape: [?]>, 
4: Tensor<name: 'reward/reward', dtype: float, shape: [?]>, 
5: Tensor<name: 'discount/discount', dtype: float, shape: [?]> 
[Op:IteratorGetNext]